"""Well-established health facts, phrased in the shared templates.

Each fact is (template key, real entity, correct option). The correct option is
always a member of that template's option pool, and no other pool member is a
defensible answer.
"""

from __future__ import annotations

KNOWN_FACTS: tuple[tuple[str, str, str], ...] = (
    # Drug -> mechanism of action
    ("mechanism", "Lisinopril", "Inhibition of angiotensin-converting enzyme"),
    ("mechanism", "Enalapril", "Inhibition of angiotensin-converting enzyme"),
    ("mechanism", "Ramipril", "Inhibition of angiotensin-converting enzyme"),
    ("mechanism", "Captopril", "Inhibition of angiotensin-converting enzyme"),
    ("mechanism", "Metoprolol", "Blockade of beta-1 adrenergic receptors"),
    ("mechanism", "Atenolol", "Blockade of beta-1 adrenergic receptors"),
    ("mechanism", "Bisoprolol", "Blockade of beta-1 adrenergic receptors"),
    ("mechanism", "Atorvastatin", "Inhibition of HMG-CoA reductase"),
    ("mechanism", "Simvastatin", "Inhibition of HMG-CoA reductase"),
    ("mechanism", "Rosuvastatin", "Inhibition of HMG-CoA reductase"),
    ("mechanism", "Pravastatin", "Inhibition of HMG-CoA reductase"),
    ("mechanism", "Omeprazole", "Irreversible inhibition of the H+/K+ ATPase"),
    ("mechanism", "Pantoprazole", "Irreversible inhibition of the H+/K+ ATPase"),
    ("mechanism", "Esomeprazole", "Irreversible inhibition of the H+/K+ ATPase"),
    ("mechanism", "Lansoprazole", "Irreversible inhibition of the H+/K+ ATPase"),
    ("mechanism", "Amlodipine", "Blockade of L-type calcium channels"),
    ("mechanism", "Nifedipine", "Blockade of L-type calcium channels"),
    ("mechanism", "Verapamil", "Blockade of L-type calcium channels"),
    ("mechanism", "Diltiazem", "Blockade of L-type calcium channels"),
    ("mechanism", "Ibuprofen", "Inhibition of cyclooxygenase-1 and -2"),
    ("mechanism", "Naproxen", "Inhibition of cyclooxygenase-1 and -2"),
    ("mechanism", "Indomethacin", "Inhibition of cyclooxygenase-1 and -2"),
    ("mechanism", "Methotrexate", "Inhibition of dihydrofolate reductase"),
    ("mechanism", "Trimethoprim", "Inhibition of dihydrofolate reductase"),
    ("mechanism", "Amoxicillin", "Inhibition of bacterial cell wall synthesis"),
    ("mechanism", "Penicillin G", "Inhibition of bacterial cell wall synthesis"),
    ("mechanism", "Cefazolin", "Inhibition of bacterial cell wall synthesis"),
    ("mechanism", "Vancomycin", "Inhibition of bacterial cell wall synthesis"),
    ("mechanism", "Morphine", "Agonism at mu-opioid receptors"),
    ("mechanism", "Fentanyl", "Agonism at mu-opioid receptors"),
    ("mechanism", "Oxycodone", "Agonism at mu-opioid receptors"),
    ("mechanism", "Warfarin", "Inhibition of vitamin K epoxide reductase"),
    # Drug -> first-line indication
    ("indication", "Metformin", "Type 2 diabetes mellitus"),
    ("indication", "Hydrochlorothiazide", "Essential hypertension"),
    ("indication", "Chlorthalidone", "Essential hypertension"),
    ("indication", "Sertraline", "Major depressive disorder"),
    ("indication", "Fluoxetine", "Major depressive disorder"),
    ("indication", "Sumatriptan", "Migraine"),
    ("indication", "Allopurinol", "Gout"),
    ("indication", "Albuterol", "Asthma"),
    ("indication", "Levothyroxine", "Hypothyroidism"),
    ("indication", "Apixaban", "Atrial fibrillation"),
    ("indication", "Levodopa", "Parkinson disease"),
    ("indication", "Adalimumab", "Rheumatoid arthritis"),
    # Disease -> gene
    ("gene", "cystic fibrosis", "CFTR"),
    ("gene", "Marfan syndrome", "FBN1"),
    ("gene", "hereditary breast and ovarian cancer syndrome", "BRCA1"),
    ("gene", "neurofibromatosis type 1", "NF1"),
    ("gene", "sickle cell disease", "HBB"),
    ("gene", "Duchenne muscular dystrophy", "DMD"),
    ("gene", "osteogenesis imperfecta", "COL1A1"),
    ("gene", "autosomal dominant polycystic kidney disease", "PKD1"),
    ("gene", "Huntington disease", "HTT"),
    ("gene", "fragile X syndrome", "FMR1"),
    ("gene", "familial adenomatous polyposis", "APC"),
    ("gene", "multiple endocrine neoplasia type 2A", "RET"),
    # Disease -> organism
    ("organism", "Lyme disease", "Borrelia burgdorferi"),
    ("organism", "tuberculosis", "Mycobacterium tuberculosis"),
    ("organism", "malaria", "Plasmodium falciparum"),
    ("organism", "syphilis", "Treponema pallidum"),
    ("organism", "pseudomembranous colitis", "Clostridioides difficile"),
    ("organism", "Q fever", "Coxiella burnetii"),
    ("organism", "listeriosis", "Listeria monocytogenes"),
    ("organism", "lobar pneumonia", "Streptococcus pneumoniae"),
    ("organism", "staphylococcal scalded skin syndrome", "Staphylococcus aureus"),
    ("organism", "hemolytic uremic syndrome", "Escherichia coli"),
    # Disease -> deficient enzyme
    ("enzyme", "Tay-Sachs disease", "Hexosaminidase A"),
    ("enzyme", "Gaucher disease", "Glucocerebrosidase"),
    ("enzyme", "phenylketonuria", "Phenylalanine hydroxylase"),
    ("enzyme", "Fabry disease", "Alpha-galactosidase A"),
    ("enzyme", "classic congenital adrenal hyperplasia", "21-hydroxylase"),
    ("enzyme", "alkaptonuria", "Homogentisate oxidase"),
    ("enzyme", "Pompe disease", "Acid alpha-glucosidase"),
    ("enzyme", "favism", "Glucose-6-phosphate dehydrogenase"),
    ("enzyme", "severe combined immunodeficiency", "Adenosine deaminase"),
)
